staging/cassandra_checks: Fix content comparison issue
When a content is not found, the comparison happens between an iterable and a
content (which is not possible). This fixes that case and improves the readability of
the actual lookup.

```
attr.exceptions.NotAnAttrsClassError: <class 'list'> is not an attrs-decorated class.
```

Refs. swh/infra/sysadm-environment#4707